---
version: "3.9"
services:
  postgres:
    image: "postgres:16.0-alpine"
    container_name: "users-postgres"
    ports:
    - "5433:5432"
    environment:
    - "POSTGRES_PASSWORD=password"
    - "POSTGRES_USER=user"
    - "POSTGRES_DB=users"
  redis:
    image: "redis:7.0-alpine"
    container_name: "users-redis"
    ports:
    - "6379:6379"
    environment:
    - "REDIS_PORT=6379"
    - "REDIS_DATABASES=1"
  envoy:
    image: "envoyproxy/envoy:dev-d3464bfd6d247530e669688c79e99c7245299df7"
    container_name: "envoy"
    ports:
    - "10000:10000"
    volumes:
    - "./envoy/envoy.yaml:/etc/envoy/envoy.yaml"
  localstack:
    container_name: "localstack"
    image: "localstack/localstack:3.0.0"
    ports:
    - "127.0.0.1:4566:4566"
    - "127.0.0.1:4510-4559:4510-4559"
    environment:
    - "DEBUG=${DEBUG-}"
    - "DOCKER_HOST=unix:///var/run/docker.sock"
    volumes:
    - "./localstack/init:/etc/localstack/init/ready.d"
    - "./localstack/bin:/opt/code/localstack/bin"
  workshop:
    build:
      dockerfile: "Dockerfile"
    container_name: "workshop"
    ports:
    - "8080:8080"
    profiles:
    - "app"
    depends_on:
      envoy:
        condition: "service_started"
      postgres:
        condition: "service_started"
      localstack:
        condition: "service_started"
      redis:
        condition: "service_started"
    volumes:
    - "../../workshop-api/build/libs/workshop-api.jar:/home/workshop/app.jar"
    environment:
    - "RDS_HOST=users-postgres"
    - "RDS_PORT=5432"
    - "RDS_DATABASE=users"
    - "RDS_USER_NAME=user"
    - "RDS_PASSWORD=password"
