---
version: "3.9"
services:
  postgres:
    image: "postgres:16.0-alpine"
    container_name: "users-postgres"
    ports:
    - "5433:5432"
    environment:
    - "POSTGRES_PASSWORD=password"
    - "POSTGRES_USER=user"
    - "POSTGRES_DB=users"
  redis:
    image: "redis:7.0-alpine"
    container_name: "users-redis"
    ports:
    - "6379:6379"
    environment:
    - "REDIS_PORT=6379"
    - "REDIS_DATABASES=1"
  envoy:
    image: "envoyproxy/envoy:dev-d3464bfd6d247530e669688c79e99c7245299df7"
    container_name: "envoy"
    ports:
    - "10000:10000"
    volumes:
    - "../envoy/envoy.yaml:/etc/envoy/envoy.yaml"
