---
version: "3.9"
services:
  sonarqube-core:
    image: "sonarqube:9.9.2-community"
    container_name: "sonarqube-core"
    depends_on:
    - "sonarqube-db"
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://sonarqube-db:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_FORCEAUTHENTICATION: false
    volumes:
    - "SonarQube_data:/opt/SonarQube/data"
    - "SonarQube_extensions:/opt/SonarQube/extensions"
    - "SonarQube_logs:/opt/SonarQube/logs"
    ports:
    - "9000:9000"
  sonarqube-db:
    image: "postgres:16.0-alpine"
    container_name: "sonarqube-db"
    environment:
      POSTGRES_USER: "sonar"
      POSTGRES_PASSWORD: "sonar"
      POSTGRES_DB: "sonar"
      POSTGRES_PORT: "5432"
    ports:
    - "5432:5432"
volumes:
  SonarQube_data: null
  SonarQube_extensions: null
  SonarQube_logs: null
